[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
test = "test"
cache_path = "cache_forge"

# Solidity compiler settings
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# EVM version
evm_version = "paris"

# Fuzz testing configuration
[fuzz]
runs = 10000
max_test_rejects = 100000

# Invariant testing configuration
[invariant]
runs = 100
depth = 500
fail_on_revert = true

# Gas reporting
gas_reports = ["*"]

# RPC endpoints
[rpc_endpoints]
bsc = "https://bsc-dataseed.binance.org/"
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545/"

# Etherscan verification
[etherscan]
bsc = { key = "${BSCSCAN_API_KEY}", chain = 56, url = "https://api.bscscan.com/api" }
bsc_testnet = { key = "${BSCSCAN_API_KEY}", chain = 97, url = "https://api-testnet.bscscan.com/api" }

# Formatting
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"

# Documentation
[doc]
out = "docs"
repository = "https://github.com/paimon-dex/paimon-dex"
